"""Offline unit tests for the GigaAM-v3 e2e RNN-T adapter.

Neither ONNX Runtime nor the staged model is needed for most of these: they
exercise the code that lives in the *adapter* — the torchaudio-parity log-mel
front-end (pinned against a golden reference generated by the upstream
preprocessor), the SentencePiece piece joining, chunk splitting, constructor
labelling, capabilities, and the buffer→final→done finalisation with a
stubbed runtime. The real decode is left to the quickstart hardware
scenarios, like the other adapters.
"""

import asyncio
import json
from pathlib import Path

import pytest

np = pytest.importorskip("numpy", reason="adapter extras not installed")

from myna.core import (
    PHASE_PREPARING,
    PHASE_READY,
    AudioFormat,
    Disposition,
    PcmChunk,
    SessionConfig,
)
from myna.testbed.gigaam import (
    GIGAAM_RATE,
    GigaAMAdapter,
    _pieces_to_text,
    _split_on_quiet,
    log_mel,
)

_GOLDEN = Path(__file__).parent / "data" / "gigaam_mel_golden.txt"


def _chirp(n: int = 32000) -> np.ndarray:
    t = np.arange(n) / 16000.0
    return (np.sin(2.0 * np.pi * (200.0 + 600.0 * t) * t) * 0.5).astype(np.float32)


class _Sink:
    def __init__(self) -> None:
        self.events: list[object] = []

    async def __call__(self, event: object) -> None:
        self.events.append(event)


async def _collect(aiter):
    out = []
    async for x in aiter:
        out.append(x)
    return out


# ── log-mel front-end ───────────────────────────────────────────────────────


def test_log_mel_matches_torchaudio_golden():
    """Pins the numpy front-end to the upstream preprocessor's output for a
    deterministic chirp (regenerate the golden with torchaudio when the
    pinned GigaAM preprocessor changes). Relative log-scale tolerance: the
    golden was computed in f32, we accumulate in f64."""
    golden = np.loadtxt(_GOLDEN)
    feats = log_mel(_chirp().astype(np.float64))
    assert feats.shape[0] == 64  # full chirp is 199 frames; golden pins the first 50
    diff = np.abs(feats[:, : golden.shape[1]] - golden)
    tol = np.maximum(0.02 * np.abs(golden), 1e-3)
    assert (diff < tol).all(), f"max diff {diff.max():.4f}"


def test_log_mel_frame_count_center_false():
    # 180640 samples -> 1 + (180640 - 320)/160 = 1128 frames (out_len parity)
    feats = log_mel(np.full(180640, 0.01, dtype=np.float64))
    assert feats.shape == (64, 1128)


def test_log_mel_short_input_is_empty():
    assert log_mel(np.zeros(100, dtype=np.float64)).shape == (64, 0)


# ── piece joining / chunk splitting ─────────────────────────────────────────


def test_pieces_to_text_word_boundary_marker():
    tokens = ["<unk>", "\u2581привет", ",", "\u2581мир"]
    assert _pieces_to_text([1, 2, 3], tokens) == "привет, мир"


def test_split_short_audio_is_single_chunk():
    samples = np.zeros(16000, dtype=np.float32)
    assert len(_split_on_quiet(samples)) == 1


def test_split_long_audio_respects_chunk_cap():
    samples = np.zeros(int(70 * GIGAAM_RATE), dtype=np.float32)
    chunks = _split_on_quiet(samples)
    assert len(chunks) >= 3
    for chunk in chunks:
        assert chunk.size <= int(24.0 * GIGAAM_RATE) + 1


# ── adapter surface ─────────────────────────────────────────────────────────


def test_candidate_and_capabilities():
    adapter = GigaAMAdapter("/models/gigaam-v3-e2e-rnnt")
    assert adapter.candidate.model == "gigaam-gigaam-v3-e2e-rnnt"
    assert adapter.candidate.engine == "gigaam-rnnt-onnx-cpu"
    assert not adapter.streaming
    caps = adapter.capabilities()
    assert caps.languages == ("ru",)
    assert caps.punctuation is True  # e2e variants emit punctuation + ITN
    assert caps.translation is False
    assert caps.input_formats[0].sample_rate_hz == GIGAAM_RATE


@pytest.mark.parametrize(
    ("rate", "channels", "width"),
    [(44100, 1, 2), (16000, 2, 2), (16000, 1, 4), (8000, 1, 2)],
)
async def test_format_rejection_is_symmetric(rate, channels, width):
    adapter = GigaAMAdapter("/models/x")
    sink = _Sink()
    fmt = AudioFormat(sample_rate_hz=rate, channels=channels, sample_width_bytes=width)

    async def audio():
        yield PcmChunk(b"\x00" * 320 * channels * width, fmt)

    await adapter.run_session(SessionConfig(audio_format=fmt), audio(), sink)
    errs = [e for e in sink.events if type(e).__name__ == "TranscriptionError"]
    assert len(errs) == 1
    assert errs[0].code == "unsupported_audio_format"


async def test_session_emits_final_then_done_with_stubbed_runtime(monkeypatch):
    """Buffer → (heartbeat) → ready → one committed final per chunk → done,
    with the ONNX runtime stubbed out (no model needed)."""
    adapter = GigaAMAdapter("/models/x")

    class _StubRuntime:
        def transcribe(self, samples: np.ndarray) -> str:
            return "Ничьих не требуя похвал,"

    async def fake_load(self):
        return _StubRuntime()

    monkeypatch.setattr(GigaAMAdapter, "_load_model", fake_load)

    sink = _Sink()
    fmt = AudioFormat(sample_rate_hz=GIGAAM_RATE, channels=1, sample_width_bytes=2)
    pcm = b"\x01\x00" * GIGAAM_RATE  # 1 s of near-silence

    async def audio():
        yield PcmChunk(pcm, fmt)

    await adapter.run_session(SessionConfig(audio_format=fmt), audio(), sink)

    kinds = [type(e).__name__ for e in sink.events]
    assert kinds[0] == "TranscriptionProgress"  # preparing heartbeat
    assert "TranscriptionProgress" in kinds
    finals = [e for e in sink.events if type(e).__name__ == "TranscriptionFinal"]
    done = [e for e in sink.events if type(e).__name__ == "TranscriptionDone"]
    assert len(finals) == 1
    assert finals[0].text == "Ничьих не требуя похвал,"
    assert finals[0].disposition == Disposition.COMMITTED
    assert len(done) == 1
    assert done[0].text == "Ничьих не требуя похвал,"
    assert kinds[-1] == "TranscriptionDone"


async def test_empty_buffer_emits_empty_done(monkeypatch):
    adapter = GigaAMAdapter("/models/x")

    class _StubRuntime:
        def transcribe(self, samples):
            return ""

    async def fake_load(self):
        return _StubRuntime()

    monkeypatch.setattr(GigaAMAdapter, "_load_model", fake_load)

    sink = _Sink()
    fmt = AudioFormat(sample_rate_hz=GIGAAM_RATE, channels=1, sample_width_bytes=2)

    async def audio():
        return
        yield  # pragma: no cover - make it an async generator

    await adapter.run_session(SessionConfig(audio_format=fmt), audio(), sink)
    done = [e for e in sink.events if type(e).__name__ == "TranscriptionDone"]
    assert len(done) == 1
    assert done[0].text == ""
